import SideBar from "@/components/SideBar";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import Login from "@/components/Login";
import ClientProvider from "@/components/ClientProvider";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "ChatGPT Clone App",
  description: "Generated by create next app and deji ice",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs min-w-[5rem] h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>

              {/* client provifer -- chatgpt notfication */}

              <ClientProvider />
              <div className="bg-[#343541] h-screen flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
